### PR TITLE
Dpgo 18/auth service

### PR DESCRIPTION
**Pull request by glbter**

### CODE REVIEW

**Comment by igkostyuk** [comment]
you may not have acces to user db

**Comment by glbter** [comment]
> 
> you may not have acces to user db

actually, this service has access to used db but in such way: only id, hash and email. No more.
other services shouldn't have access to user hash and email (except email service has email), because it's not their's responsibility

**Comment by igkostyuk** [comment]
> > you may not have acces to user db
> 
> actually, this service has access to used db but in such way: only id, hash and email. No more.
> other services shouldn't have access to user hash and email (except email service has email), because it's not their's responsibility

we agree week ago, that we separate user and auth microservices, so user microservice response for his own data.

**Comment by glbter** [comment]
> > > you may not have acces to user db
> 
> > 
> 
> > actually, this service has access to used db but in such way: only id, hash and email. No more.
> 
> > other services shouldn't have access to user hash and email (except email service has email), because it's not their's responsibility
> 
> 
> 
> we agree week ago, that we separate user and auth microservices, so user microservice response for his own data.

And Im talking about that, don't I? Or I think about it in other way? :) Any suggestions?

**Comment by igkostyuk** [comment]
> > > > you may not have acces to user db
> > 
> > 
> > > 
> > 
> > 
> > > actually, this service has access to used db but in such way: only id, hash and email. No more.
> > 
> > 
> > > other services shouldn't have access to user hash and email (except email service has email), because it's not their's responsibility
> > 
> > 
> > we agree week ago, that we separate user and auth microservices, so user microservice response for his own data.
> 
> And Im talking about that, don't I? Or I think about it in other way? :) Any suggestions?

you trying to direct change data in other service db and duplicate functionality. communicate with the service not a service db

**Comment by glbter** [comment]
> > > > > you may not have acces to user db
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > actually, this service has access to used db but in such way: only id, hash and email. No more.
> 
> > > 
> 
> > > 
> 
> > > > other services shouldn't have access to user hash and email (except email service has email), because it's not their's responsibility
> 
> > > 
> 
> > > 
> 
> > > we agree week ago, that we separate user and auth microservices, so user microservice response for his own data.
> 
> > 
> 
> > And Im talking about that, don't I? Or I think about it in other way? :) Any suggestions?
> 
> 
> 
> you trying to direct change data in other service db and duplicate functionality. communicate with the service not a service db

But wait... the passwords is the auth service's functionality

**Comment by igkostyuk** [comment]
> > > > > > you may not have acces to user db
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > actually, this service has access to used db but in such way: only id, hash and email. No more.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > other services shouldn't have access to user hash and email (except email service has email), because it's not their's responsibility
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > we agree week ago, that we separate user and auth microservices, so user microservice response for his own data.
> > 
> > 
> > > 
> > 
> > 
> > > And Im talking about that, don't I? Or I think about it in other way? :) Any suggestions?
> > 
> > 
> > you trying to direct change data in other service db and duplicate functionality. communicate with the service not a service db
> 
> But wait... the passwords is the auth service's functionality

do you need hold passwords ? other services can create user ?

**Comment by glbter** [comment]
> > > > > > > you may not have acces to user db
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > actually, this service has access to used db but in such way: only id, hash and email. No more.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > other services shouldn't have access to user hash and email (except email service has email), because it's not their's responsibility
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > we agree week ago, that we separate user and auth microservices, so user microservice response for his own data.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > And Im talking about that, don't I? Or I think about it in other way? :) Any suggestions?
> 
> > > 
> 
> > > 
> 
> > > you trying to direct change data in other service db and duplicate functionality. communicate with the service not a service db
> 
> > 
> 
> > But wait... the passwords is the auth service's functionality
> 
> 
> 
> do you need hold passwords ? other services can create user ?

1 yes. In other way, there is bo sense in microservice
2 it depends on what data we are talking about.
I suggest to think it through on Monday

**Pull request closed without merging**
